@extends('layouts.main')

@section('title',"Главная")

@section('content')
<div class="container">
    <table>
        <tr>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
        </tr>
        <tr>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
        </tr>
        <tr>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
        </tr>
        <tr>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
        </tr>
        <tr>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
            <td>день</td>
        </tr>
    </table>
</div>
@endsection
